Make `cyclonedds typeof` work on derived types (#243)
* Make `cyclonedds typeof` work on derived types

This solves

   File "/usr/lib64/python3.11/site-packages/cyclonedds/idl/init.py", line 39, \
   in make_idl_struct \
     bases = tuple(list(*bases) + [IdlStruct])
                   ^^^^^^^^^^^^
   TypeError: 'IdlMeta' object is not iterable

when `cyclonedds typeof` is used to print a derived type.

Signed-off-by: Erik Boasson <eb@ilities.com>